const exportTpl =
`/* Automatically generated by './build/add-module.js' */
import module from '@/modules/{{moduleName}}/{{moduleName}}';
import routes from '@/modules/{{moduleName}}/{{moduleName}}.router.js';
import store from '@/store/modules/{{moduleName}}';
import config from '@/utils/config.utils';
import locale from '@/i18n/locale';

export default {
  module,
  routes,
  store: { {{camelModuleName}}: store },
  locale: { {{camelModuleName}}: locale.{{camelModuleName}} },
  config
};
`;

module.exports = exportTpl;
