const storeTpl =
`/* Automatically generated by './build/add-module.js' */
const {{camelModuleName}} = {
  namespaced: true,
  state: {},
  mutations: {},
  actions: {},
  getters: {}
};

export default {{camelModuleName}};
`;

module.exports = storeTpl;
